server:
  port: 8091

spring:
  application:
    name: auth-service
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: nexus-auth-client
            client-secret: ICdEmE4XwvcC1HMLydpsuYwUh9pp0eHm
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/nexus-realm

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/